import { test, expect } from '@playwright/test';

test('basic test', async ({ page }) => {
  await page.goto('https://codemama.io/');
  await page.getByRole('link').filter({ hasText: /^$/ }).first().click();
  await page.getByText('Test yourCoding ability now').click();
  await page.getByText('Coding ability now').click();
  await page.getByRole('button', { name: 'Solve problems', exact: true }).click();
  await page.goto('https://codemama.io/');
  await page.getByRole('paragraph').filter({ hasText: 'Md Alhaz Mondal Hredhay' }).click();
  await page.getByRole('paragraph').filter({ hasText: 'H. M. Masum Billah' }).click();
  await page.getByRole('paragraph').filter({ hasText: 'S M Ali Ahsan Al Jabir' }).click();
  await page.locator('div').filter({ hasText: /^Md Alhaz Mondal Hredhay100%Score$/ }).getByRole('img').first().click();
  await page.getByRole('link', { name: 'ফ্রিতে রেজিঃ করুন Code' }).click();
  await page.getByRole('button', { name: 'Try Free Test' }).click();
  await page.getByRole('main').getByRole('link').filter({ hasText: /^$/ }).click();
  await page.getByRole('link', { name: 'ব্যাচ ২ ৭৬ সিট বাকি ২৬ দিন বাকি Mastering DevOps: From Fundamentals to Advanced' }).click();
//   await page.getByRole('link', { name: 'ব্যাচ ২ ৭৬ সিট বাকি ২৬ দিন বাকি Mastering DevOps: From Fundamentals to Advanced' }).getByRole('button').click();
  await page.getByRole('paragraph').filter({ hasText: 'প্রোমো কোড' }).click();
  await page.getByRole('textbox').fill('Devops35');
  await page.getByRole('button', { name: 'এপ্লাই' }).click();
  await page.getByTitle('Understanding DevOps and SDLC').getByRole('img').first().click();
  await page.getByText('Live Class 1: What is DevOps').click();
  await page.getByTitle('Understanding DevOps and SDLC').getByRole('img').first().click();
  await page.getByText('Live Class 2: DevOps in').click();
  await page.getByText('Version Control and CI/CD').click();
  await page.getByText('Live Class 1: Advanced Git').click();
  await page.getByText('Version Control and CI/CD').click();
  await page.getByText('Live Class 2: Automation').click();
  await expect(page.locator('#study_plan')).toContainText('Building CI/CD Pipelines (Module 3-4)');
  await page.getByText('CI/CD Pipeline Fundamentals').click();
  await page.getByText('Live Class 1: Introduction to CI/CD Pipelines').click();
  await page.getByText('CI/CD Pipeline Fundamentals').click();
  await page.getByText('Live Class 2: Deploying to').click();
  await page.getByText('Infrastructure as Code (IaC)').click();
  await page.getByText('Live Class 1: Introduction to Infrastructure as Code').click();
  await page.getByText('Infrastructure as Code (IaC)').click();
  await page.getByText('Live Class 2: Automating').click();
  await page.getByRole('button', { name: 'আরো দেখুন' }).click();
});